import Head from 'next/head'
import { useSession, signIn, signOut } from 'next-auth/react'
import axios from 'axios'
import { useEffect, useState } from 'react'
import Image from 'next/image'
import { ISession, IUserInfo } from '@/common/interfaces'
import NoteComponent from '@/components/noteComponent'

export default function Home() {
  const { data } = useSession()
  const session = data as ISession

  // Create states to store user info and photo
  const [userInfo, setUserInfo] = useState<IUserInfo>()

  /**
   * Fetch user info and photo when session is available
   * Set the states
   * Pass the token in the header
   */
  useEffect(() => {
    const getUserInfo = async () => {
      const response = await axios.get('/api/me/profile', { headers: { token: session?.accessToken } })
      setUserInfo(response.data.data)
    }

    if (session) {
      getUserInfo()
    }
  }, [session])

  /**
   * Create a new document
   */
  const createDocument = async () => {
    const response = await axios.post('/api/create-doc', {}, { headers: { token: session?.accessToken } })
    console.log(response.data)
  }

  /**
   * If session is available, display user info and photo
   */
  if (session)
    return (
      <>
        <Head>
          <title>Five Year Calendar</title>
          <meta name='description' content='Generated by create next app' />
          <meta name='viewport' content='width=device-width, initial-scale=1' />
          <link rel='icon' href='/favicon.ico' />
        </Head>

        <main>
          <button
            onClick={() => {
              signOut()
            }}
          >
            Sign Out
          </button>

          {/* preview user photo from userInfo.picture if the state was not null */}
          {userInfo?.picture && <Image src={userInfo.picture} width={100} height={100} alt='profile photo' />}

          {/* display user info from userinfo.data if the state was not null */}
          <h1>Hi {userInfo?.given_name}</h1>

          <button onClick={createDocument}>Create Test Document</button>


          <NoteComponent />
        </main>
      </>
    )

  /**
   * If session is not available, display sign in button
   */
  return <button onClick={() => signIn('google')}>Sign In</button>
}
