import Head from 'next/head'
import { useSession, signIn, signOut } from 'next-auth/react'
import axios from 'axios'
import { useEffect, useState } from 'react'
import Image from 'next/image'

interface ISession {
  accessToken: string
  expires: string
  expires_in: string
  id_token: string
  refresh_token: string
  token_type: string
  user: {
    name: string
    email: string
    image: string
  }
}

export default function Home() {
  const { data } = useSession()
  const session = data as ISession

  if (session) console.log(session.accessToken)

  // Create states to store user info and photo
  const [userInfo, setUserInfo] = useState({ givenName: ' ' })
  const [userPhoto, setUserPhoto] = useState(null)

  useEffect(() => {
    const getUserInfo = async () => {
      const response = await axios.get('https://graph.microsoft.com/v1.0/me', {
        headers: { Authorization: `Bearer ${session.accessToken}` },
      })
      console.log(response.data.data)
    }

    if (session) getUserInfo()
  }, [session])

  /**
   * Fetch user info and photo when session is available
   * Set the states
   * Pass the token in the header
   */
  useEffect(() => {
    const getUserInfo = async () => {
      const response = await axios.get('/api/me/profile', { headers: { token: session?.accessToken } })
      setUserInfo(response.data.data)
    }

    const getUserPhoto = async () => {
      // const response = await axios.get('/api/me/photo', { headers: { token: session?.accessToken } })
      // setUserPhoto(response.data.data)
    }

    if (session) {
      getUserInfo()
      getUserPhoto()
    }
  }, [session])

  if (session)
    return (
      <>
        <Head>
          <title>Five Year Calendar</title>
          <meta name='description' content='Generated by create next app' />
          <meta name='viewport' content='width=device-width, initial-scale=1' />
          <link rel='icon' href='/favicon.ico' />
        </Head>

        <main>
          <button
            onClick={() => {
              signOut()
            }}
          >
            Sign Out
          </button>

          {/* preview user photo from userphoto.data if the state was not null */}
          {/* {userPhoto && <img src={`data:image/png;base64,${userPhoto}`} alt='profile image' />} */}

          {/* display user info from userinfo.data if the state was not null */}
          <h1>Hi {userInfo?.givenName}</h1>
        </main>
      </>
    )

  return <button onClick={() => signIn('azure-ad')}>Sign In</button>
}
